package biz.belcorp.consultoras.util.anotation;

import android.support.annotation.StringDef;

import java.lang.annotation.Retention;

import static java.lang.annotation.RetentionPolicy.SOURCE;

@Retention(SOURCE)
@StringDef({
    BusinessErrorCode.DEFAULT,
    BusinessErrorCode.INTERNO,

    BusinessErrorCode.PEDIDO_STOCK_ESTRATEGIA,
    BusinessErrorCode.PEDIDO_LOCK_GPR,
    BusinessErrorCode.PEDIDO_LOCK_RESERVADO,
    BusinessErrorCode.PEDIDO_LOCK_HORARIO_RESTRINGIDO,
    BusinessErrorCode.PRODUCTO_NO_ENCONTRADO,
    BusinessErrorCode.PRODUCTO_STOCK_INVALIDO,

    BusinessErrorCode.GENERIC,
    BusinessErrorCode.VALIDACION,
    BusinessErrorCode.AUTENTICACION_INVALIDA,
    BusinessErrorCode.AUTENTICACION_USUARIO_NOEXISTE,
    BusinessErrorCode.AUTENTICACION_USUARIO_NOAUTORIZADO,
    BusinessErrorCode.AUTENTICACION_USUARIO_NOPASAPEDIDO,
    BusinessErrorCode.AUTENTICACION_USUARIO_CORREO_EXISTE,

    BusinessErrorCode.OFERTA_INPUT_INVALIDO,

    BusinessErrorCode.RECUPERA_CONTRASENIA_CEDULANOEXISTE,
    BusinessErrorCode.RECUPERA_CONTRASENIA_CORREONOREGISTRADO,
    BusinessErrorCode.RECUPERA_CONTRASENIA_CORREONOIDENTIFICADO,

    BusinessErrorCode.ACTUALIZA_MIS_DATOS_CORREOYAEXISTE,

    BusinessErrorCode.SINCRONIZACION_CONTACTOPRINCIPALNOEXISTE,
    BusinessErrorCode.SINCRONIZACION_CLIENTENOREGISTRADO,
    BusinessErrorCode.SINCRONIZACION_CLIENTENOACTUALIZADO,
})
public @interface BusinessErrorCode {
    String DEFAULT = "0000";
    String INTERNO = "9999";

    String PEDIDO_STOCK_ESTRATEGIA = "0001";
    String PEDIDO_LOCK_GPR = "0002";
    String PEDIDO_LOCK_RESERVADO = "0003";
    String PEDIDO_LOCK_HORARIO_RESTRINGIDO = "0004";
    String PRODUCTO_NO_ENCONTRADO = "0005";
    String PRODUCTO_STOCK_INVALIDO = "0006";

    String GENERIC = "1001";
    String VALIDACION = "1002";
    String AUTENTICACION_INVALIDA = "1003";
    String AUTENTICACION_USUARIO_NOEXISTE = "1004";
    String AUTENTICACION_USUARIO_NOAUTORIZADO = "1005";
    String AUTENTICACION_USUARIO_NOPASAPEDIDO = "1006";
    String AUTENTICACION_USUARIO_CORREO_EXISTE = "1007";

    String OFERTA_INPUT_INVALIDO = "2001";

    String RECUPERA_CONTRASENIA_CEDULANOEXISTE = "5001";
    String RECUPERA_CONTRASENIA_CORREONOREGISTRADO = "5002";
    String RECUPERA_CONTRASENIA_CORREONOIDENTIFICADO = "5003";

    String ACTUALIZA_MIS_DATOS_CORREOYAEXISTE = "6001";

    String SINCRONIZACION_CONTACTOPRINCIPALNOEXISTE = "7001";
    String SINCRONIZACION_CLIENTENOREGISTRADO = "7002";
    String SINCRONIZACION_CLIENTENOACTUALIZADO = "7003";
    String SINCRONIZACION_CLIENTEYAEXISTENTE = "7009";
    String SINCRONIZACION_CLIENTENOELIMINADO = "7013";
}
